name: universal_ble_fork
description: A cross-platform (Android/iOS/macOS/Windows/Linux/Web) Bluetooth Low Energy (BLE) plugin for Flutter
version: 0.21.2
repository: https://github.com/BDR-Thermea-B2B-apps/universal_ble

topics:
  - bluetooth-low-energy-ble
  - core-bluetooth
  - windows-devices-bluetooth
  - bluez
  - web-bluetooth

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  flutter_web_bluetooth: ^1.1.0
  bluez: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^22.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bdrthermea.universal_ble
        pluginClass: UniversalBlePlugin
      ios:
        pluginClass: UniversalBlePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: UniversalBlePlugin
        sharedDarwinSource: true
      windows:
        pluginClass: UniversalBlePluginCApi
